### ISSUE TITLE
Windows Defender identifies binary as trojan

### ISSUE THREAD

**Issue by conioh** [hfiref0x/WinObjEx64#1]
Identified as: Win32/Spallowz.A!cl

> **Category**: Trojan
> 
> **Description**: This program is dangerous and executes commands from an attacker.
> 
> **Recommended** action: Remove this software immediately.
> 
> **Items**: 
> file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\260A5552-CCD4-7324-ECB2-4F4BC7C2A253_1d1ce1b1363ccb0
> file:C:\Users\Alex\Desktop\WinObjEx64.exe
> webfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{9D978906-6B4F-4B93-8A83-89B5389F0367}-260A5552-CCD4-7324-ECB2-4F4BC7C2A253_1d1ce1b1363ccb0|chrome.exe
> webfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\260A5552-CCD4-7324-ECB2-4F4BC7C2A253_1d1ce1b1363ccb0|https://raw.githubusercontent.com/hfiref0x/WinObjEx64/master/Compiled/WinObjEx64.exe|chrome.exe
> webfile:C:\Users\Alex\Desktop\WinObjEx64.exe|https://raw.githubusercontent.com/hfiref0x/WinObjEx64/master/Compiled/WinObjEx64.exe|chrome.exe
> 
> Get more information about this item online.

**Comment by hfiref0x** [comment]
Microsoft problem. I will not waste my time contacting any AV regarding their schizophrenic detections and will not do anything to "bypass" this detect. This project is open source. If you have any doubts about it, look inside, nothing is hidden.

**Comment by hfiref0x** [comment]
Another one report about MS detection on binary.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Azden.B!cl

https://twitter.com/gN3mes1s/status/935989615877611522

**Comment by TPS** [comment]
The zip of today's binary passes just fine.: https://www.virustotal.com/#/url/db3d4eff950230df55ed9b24da8df8ded0fb078b810961239d176c9fb1bc7b7f/detection

I suppose that means the binary inside should be OK, too.

**Comment by TPS** [comment]
Yep, the .exe's fine, too.:
https://www.virustotal.com/#/file/fc101b477b9ef14b817b8340557d70bb5eda5da867474610541a9ca53744e0d1/detection
