### ISSUE TITLE
Run as LocalSystem is not reliable

### ISSUE THREAD

**Issue by diversenok** [hfiref0x/WinObjEx64#14]
**Describe the bug**
Sometimes the "Run as LocalSystem" feature fails. It occurs because `supxGetSystemToken` returns the first system token it finds, which might happen to be a token of a restricted service.

**To Reproduce**
Most frequently it happens when WinObjEx64 runs under an administrative account that does not have SeDebugPrivilege.

**Screenshots**
On the screenshot you can see that after `supxGetSystemToken` returns a restricted token and  `supRunAsLocalSystem` impersonates it, the function silently fails because it is unable to change token's session ID without SeTcbPrivilege,

![WinObjEx64-RunAsSystem](https://user-images.githubusercontent.com/30962924/60383531-b67f6280-9a7a-11e9-8d72-5ce3c95a552f.png)

**Environment**
Tested it on Windows 7.

**Additional context**
In fact, the reason why without SeDebugPrivilege `supxGetSystemToken` returns a restricted token (or even no token in some cases) is that you use `PROCESS_QUERY_INFORMATION` instead of `PROCESS_QUERY_LIMITED_INFORMATION`.

https://github.com/hfiref0x/WinObjEx64/blob/84a75c455cb872ed65e901843f5281f76a93f0f5/Source/WinObjEx64/sup.c#L3697-L3700

While administrators have high integrity,  Mandatory Integrity Control prevents them from opening system processes for _read_ and _write_ access. This happens because `PROCESS_QUERY_INFORMATION` is considered as a denied _read_ access while `PROCESS_QUERY_LIMITED_INFORMATION` is an allowed _execute_ access. So, changing `PROCESS_QUERY_INFORMATION` to `PROCESS_QUERY_LIMITED_INFORMATION` might solve most of the problems and make this feature work even without SeDebugPrivilege.

Preferably, `supxGetSystemToken` should not rely on any particular process order. You might just want to use winlogon's token, or, perhaps, add some checks to make sure you are using the right security context.

And showing an error message in case something went wrong would be useful.

**Comment by hfiref0x** [comment]
This will be fixed in next version.

**Comment by hfiref0x** [comment]
It has been changed in 1.8.0
