### ISSUE TITLE
Cannot list IRPs for drivers

### ISSUE THREAD

**Issue by NtSanya** [hfiref0x/WinObjEx64#29]
For some reason I cannot see the object tab in the driver properties for displaying the IRPs for drivers.

I already have set testsigning and local debugging enabled:

![testsigning](https://user-images.githubusercontent.com/102448486/176030742-875d3dc8-8278-408c-877b-f105b2253bac.png)

![debgsettings](https://user-images.githubusercontent.com/102448486/176030870-986798ef-4e6f-4829-925f-a025a2e5cc97.png)

I rebooted the machine for the effects to take place, but I'm still not able to see any IRPs. What gives?

**Comment by hfiref0x** [comment]
Test signing is not required.
Show the output of View->System Information, fields

Driver.LoadStatus
Driver.OpenStatus
Driver.IsOurLoad
Driver.SelectedProvider

**Comment by NtSanya** [comment]
you're right, i didn't enable debug mode. I did it now and Driver.IsOurLoad is TRUE and can see the IRPs, thanks!
