### ISSUE TITLE
Compile Error for x86

### ISSUE THREAD

**Issue by MagicAndre1981** [hfiref0x/WinObjEx64#3]
The code can't be compiled for x86.

in propObjectDump.c I had to add `#if defined(_AMD64_) `around the hint call because according to the `WDM.h` for Build 14939 this field is only avaiable for x64.

```
typedef struct _KDEVICE_QUEUE {
    CSHORT Type;
    CSHORT Size;
    LIST_ENTRY DeviceListHead;
    KSPIN_LOCK Lock;

#if defined(_AMD64_)

    union {
        BOOLEAN Busy;
        struct {
            LONG64 Reserved : 8;
            LONG64 Hint : 56;
        };
    };

#else

    BOOLEAN Busy;

#endif

} KDEVICE_QUEUE, *PKDEVICE_QUEUE, *PRKDEVICE_QUEUE;
```

Now I still get this error:

> propSecurity.c(471): error C2440: '=': cannot convert from 'void (__cdecl *)(IObjectSecurity *,HANDLE)' to 'PCLOSEOBJECTMETHOD'

**Comment by hfiref0x** [comment]
Sure it can't be compiled for x86. Because it's WinObjEx<64> isn't it?

**Comment by MagicAndre1981** [comment]
it would be nice to have the tool in both architectures. My 8" Tablet is still 32Bit, so I would like to have working, Mark's Winobj is too old
