### ISSUE TITLE
WinGet install fails without elevation

### ISSUE THREAD

**Issue by sharpjs** [hfiref0x/WinObjEx64#34]
**Describe the bug**
WinGet install fails with error `0x80070005 : Access is denied` if run from a non-elevated prompt.

**To Reproduce**
```ps1
winget install -i WinObjEx64
```

**Expected behavior**
![image](https://github.com/hfiref0x/WinObjEx64/assets/708461/30b1dc04-dba8-447a-b6f8-977e7454fbba)

**Screenshots**
![image](https://github.com/hfiref0x/WinObjEx64/assets/708461/69c7231a-7c19-4635-823e-283a53a92b1f)

**Environment**
Windows 11 23H2, build 22631.3235

**Comment by hfiref0x** [comment]
WinObjEx64 doesn't require elevation to start.

**Comment by sharpjs** [comment]
@hfiref0x: WinObjEx64 does not fail.  The **WinGet install** is what fails.

**Comment by hfiref0x** [comment]
I've never produced any winget installs for this program and have no idea who did that. Guess this is not my fault.

**Comment by sharpjs** [comment]
Fair enough.  Yeah, looking [at the manifests](https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/hfiref0x/WinObjEx64/2.0.4), it was @w3lld0ne, not you.  I'll close this and see if there's any way to raise the issue with @w3lld0ne or just submit a PR for it myself.  Sorry for the bother.

**Comment by w3lld0ne** [comment]
@sharpjs this seems like not an issue with the package (it installs perfectly fine for me on clean VM from unelevated terminal), but with your WinGet instance or smth.
