### ISSUE TITLE
Show "??" entry in the list

### ISSUE THREAD

**Issue by alabuzhev** [hfiref0x/WinObjEx64#38]
Object Explorer shows the content of "\\" by calling `NtQueryDirectoryObject` recursively.
This approach overlooks one particular directory - `??` (a.k.a. "local `\DosDevices`"), which is not returned when querying the root directory, unlike the global version of `\DosDevices` (`GLOBAL??`).
This directory typically contains a symbolic link to `Global`, network drives, subst drives and whatever else the user defined with `DefineDosDevice`.

This information is also available under `\Sessions\<SESSION_ID>\DosDevices\<LOGON_SESSION_ID>`, but getting there is more cumbersome and requires Administrator rights.

It can be added manually (I'm not familiar with the code, so apologies if something is horribly wrong):
```DIFF
diff --git a/Source/WinObjEx64/kldbg.c b/Source/WinObjEx64/kldbg.c
index 0d5b62e..1477191 100644
--- a/Source/WinObjEx64/kldbg.c
+++ b/Source/WinObjEx64/kldbg.c
@@ -70,6 +70,12 @@ static UNICODE_STRING g_usGlobalNamespace = {
     OB_GLOBALNAMESPACE
 };
 
+static UNICODE_STRING g_usLocalDevices = {
+    sizeof(OB_LOCALDEVICES) - sizeof(WCHAR),
+    sizeof(OB_LOCALDEVICES),
+    OB_LOCALDEVICES
+};
+
 /*
 * ObGetPredefinedUnicodeString
 *
@@ -94,6 +100,8 @@ PUNICODE_STRING ObGetPredefinedUnicodeString(
     case OBP_ROOT:
     default:
         return &g_usObjectsRootDirectory;
+    case OBP_LOCALDEVICES:
+        return &g_usLocalDevices;
     }
 }
 
diff --git a/Source/WinObjEx64/kldbg.h b/Source/WinObjEx64/kldbg.h
index 7cf596d..422ef1a 100644
--- a/Source/WinObjEx64/kldbg.h
+++ b/Source/WinObjEx64/kldbg.h
@@ -100,6 +100,7 @@
 #define OBTYPES_DIRECTORY       L"\\ObjectTypes"
 #define OB_GLOBALROOT           L"\\GLOBAL??\\GLOBALROOT"
 #define OB_GLOBALNAMESPACE      L"\\??"
+#define OB_LOCALDEVICES         L"??"
 
 #define OBJECT_SHIFT 8
 
@@ -135,6 +136,7 @@ typedef ULONG_PTR *PUTable;
 #define OBP_OBTYPES         2 
 #define OBP_GLOBAL          3
 #define OBP_GLOBALNAMESPACE 4  
+#define OBP_LOCALDEVICES    5
 
 //enum with information flags used by ObGetObjectHeaderOffset
 typedef enum _OBJ_HEADER_INFO_FLAG {
diff --git a/Source/WinObjEx64/list.c b/Source/WinObjEx64/list.c
index aa83f34..d9d2c4e 100644
--- a/Source/WinObjEx64/list.c
+++ b/Source/WinObjEx64/list.c
@@ -346,6 +346,12 @@ VOID xxxListObjectDirectoryTree(
 
     } while (TRUE);
 
+    xxxListObjectDirectoryTree(HeapHandle,
+        ObGetPredefinedUnicodeString(OBP_LOCALDEVICES),
+        directoryHandle,
+        ViewRootHandle,
+        prevItem);
+
     NtClose(directoryHandle);
 }
 
```

The result:

![image](https://github.com/hfiref0x/WinObjEx64/assets/11453922/b075287a-7586-4a43-a1d2-428f5dc5272f)

Links:
https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/local-and-global-ms-dos-device-names
https://www.osronline.com/article.cfm%5Earticle=381.htm
https://superuser.com/questions/884347/win32-and-the-global-namespace
https://stackoverflow.com/questions/4686897/sessions-window-stations-and-desktops

**Comment by hfiref0x** [comment]
The problem is that there is no such object, it doesn't exist. It is internal redirection made by MS for easy use in all of their mess for compatibility reasons.

All your local ?? symlink objects are stored inside \Sessions\<SessionId>\DosDevices\<LogonSessionId> as you said and when you specify \\?? this is translated to real object directory (e.g. \Sessions\0\DosDevices\00000000-0004bd70) by API internally. Adding what you suggest will bring mess as there is no clear indication what is "real" object and what is just hardcoded virtual name redirector.
